version: "3.9"

services:
  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --loose --location /workspace --debug /workspace/debug.log"
      ports:
        - 10000:10000
        - 10001:10001
        - 10002:10002
      volumes:
        - ./azurite:/workspace

  # app:
  #   build: .
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - azurite