version: "3.9"

services:
  azurite:
      image: mcr.microsoft.com/azure-storage/azurite
      command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --loose --location /workspace --debug /workspace/debug.log"
      ports:
        - 10000:10000
      volumes:
        - ./azurite:/workspace

  app:
    build: .
    ports:
      - 8080:80
    depends_on:
      - azurite